version: "3.4"

services:
  ml-server:
    build:
      context: .
      dockerfile: Dockerfile
    command:
          - sh
          - -c
          - "python server.py"
    ports:
      - "5000:5000"